version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
  friday:
    build: .
    container_name: friday 
    environment:
      HOST: "0.0.0.0"
      PORT: "5000" 
      DATABASE_URL: "sqlite:friday.db" 
